version: '3.4'

services:
  pokemonapi:
    image: ${DOCKER_REGISTRY-}pokemonapi
    environment:
      INITDATABASE: true
      CONNECTIONSTRINGS__DEFAULTCONNECTION: Server=database;Database=PokemonWEB;User Id=SA;Password=db@TMS-NET-17;
    build:
      context: .
      dockerfile: PokemonAPI/Dockerfile
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "db@TMS-NET-17"
      ACCEPT_EULA: "Y"
  helperapi:
    image: ${DOCKER_REGISTRY-}helperapi