name: Build
  
on:
  push:
    branches: [ "develop", "main" ]

env:
  ROUTE_TO_POK: ./GraduationAPI/PokemonAPI2.0
  DEVELOP_REF: kakoyto_dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Enviromment
      run: |
        echo "OUTPUT=$GITHUB_WORKSPACE/output" >> $GITHUB_ENV
        echo "Output folder is"
        echo "$OUTPUT"
    
    - name: Develop
      if: ${{ env.DEVELOP_REF == 'refs/heads/develop'}}
      run: echo "Running develop"
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run:  dotnet restore      
      working-directory: ${{ env.ROUTE_TO_POK }}

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.ROUTE_TO_POK }}

    - name: Test
      run: dotnet test --no-build --verbosity normal      
      working-directory: ${{ env.ROUTE_TO_POK }}
      
    - name: Pack      
      working-directory: ${{ env.ROUTE_TO_POK }}
      run: dotnet publish --configuration Release --output $OUTPUT
    
    - name: Create Deliverable
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build Result
        path: ${{ env.OUTPUT }}
